ExploreSV.WebApplication/Controllers/CategoryController.cs
using ExploreSV.BusinessLogic.DTOs;
using ExploreSV.BusinessLogic.UseCases.Categories.Commands.CreateCategory;
using ExploreSV.BusinessLogic.UseCases.Categories.Commands.DeleteCategory;
using ExploreSV.BusinessLogic.UseCases.Categories.Queries.GetCategory;
using ExploreSV.BusinessLogic.UseCases.Categories.Queries.GetCategories;
using Mapster;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ExploreSV.WebApplication.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        private readonly IMediator _mediator;

        public CategoryController(IMediator mediator)
        {
            _mediator = mediator;
        }
        public async Task<IActionResult> Index(int pageNumber = 1, int pageSize = 6)
        {
            var query = new GetCategoriesQuery
            {
                PageNumber = pageNumber,
                PageSize = pageSize
            };
            var categories = await _mediator.Send(query);
            return View(categories);
        }

        //GET: CategoryController/Create
        public ActionResult Create()
        {
            return View();
        }

        //POST: CategorytController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateCategoryRequest createCategoryRequest)
        {
            try
            {
                var result = await _mediator.Send(new CreateCategoryCommand(createCategoryRequest));
                if (result > 0)
                    return RedirectToAction(nameof(Index));
                else
                    throw new Exception("Sucedio un error al intentar guardar la nueva Categoria");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(createCategoryRequest);
            }
        }

        //GET: CategoryController/Delete
        public async Task<IActionResult> Delete(int id)
        {
            var category = await _mediator.Send(new GetCategoryQuery(id));
            return View(category);
        }

        //POST: CategoryController/Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, CategoryResponse categoryResponse)
        {
            try
            {
                var result = await _mediator.Send(new DeleteCategoryCommand(id));
                if (result > 0)
                    return RedirectToAction(nameof(Index));
                else
                    throw new Exception("Sucedio un error al intentar eliminar la Categoria");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(categoryResponse);
            }
        }
    }
}

ExploreSV.WebApplication/Controllers/DepartmentController.cs
using ExploreSV.BusinessLogic.DTOs;
using ExploreSV.BusinessLogic.UseCases.Departments.Commands.CreateDepartment;
using ExploreSV.BusinessLogic.UseCases.Departments.Commands.DeleteDepartment;
using ExploreSV.BusinessLogic.UseCases.Departments.Queries.GetDepartment;
using ExploreSV.BusinessLogic.UseCases.Departments.Queries.GetDepartments;
using Mapster;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ExploreSV.WebApplication.Controllers
{
    [Authorize]
    public class DepartmentController : Controller
    {
        private readonly IMediator _mediator;

        public DepartmentController(IMediator mediator)
        {
            _mediator = mediator;
        }

        public async Task<IActionResult> Index(int pageNumber = 1, int pageSize = 6)
        {
            var query = new GetDepartmentsQuery
            {
                PageNumber = pageNumber,
                PageSize = pageSize
            };
            var departments = await _mediator.Send(query);
            return View(departments);
        }

        //GET: DepartmentController/Create
        public ActionResult Create()
        {
            return View();
        }

        //POST: DepartmentController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateDepartmentRequest createDepartmentRequest)
        {
            try
            {
                var result = await _mediator.Send(new CreateDepartmentCommand(createDepartmentRequest));
                if (result > 0)
                    return RedirectToAction(nameof(Index));
                else
                    throw new Exception("Sucedio un error al intentar guardar el nuevo Departamento");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(createDepartmentRequest);
            }
        }

        //GET: DepartmentController/Delete
        public async Task<IActionResult> Delete(int id)
        {
            var department = await _mediator.Send(new GetDepartmentQuery(id));
            return View(department);
        }

        //POST: DepartmentController/Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, DepartmentResponse departmentResponse)
        {
            try
            {
                var result = await _mediator.Send(new DeleteDepartmentCommand(id));
                if (result > 0)
                    return RedirectToAction(nameof(Index));
                else
                    throw new Exception("Sucedio un error al intentar eliminar el Departamento");
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(departmentResponse);
            }
        }
    }
}

ExploreSV.WebApplication/Controllers/StatusController.cs
using ExploreSV.BusinessLogic.DTOs;
using ExploreSV.BusinessLogic.UseCases.Statuses.Commands.CreateStatus;
using ExploreSV.BusinessLogic.UseCases.Statuses.Commands.DeleteStatus;
using ExploreSV.BusinessLogic.UseCases.Statuses.Commands.UpdateStatus;
using ExploreSV.BusinessLogic.UseCases.Statuses.Queries.GetStatus;
using ExploreSV.BusinessLogic.UseCases.Statuses.Queries.GetStatuses;
using Mapster;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ExploreSV.WebApplication.Controllers
{
    [Authorize]
    public class StatusController : Controller
    {
        private readonly IMediator _mediator;

        public StatusController(IMediator mediator)
        {
            _mediator = mediator;
        }
        public async Task<IActionResult> Index()
        {
            var statuses = await _mediator.Send(new GetStatusesQuery());
            return View(statuses);
        }

        //GET: StatusController/Create
        public ActionResult Create()
        {
            return View();
        }

        //POST: StatusController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateStatusRequest createStatusRequest)
        {
            try
            {
                var result = await _mediator.Send(new CreateStatusCommand(createStatusRequest));
                if (result > 0)
                    return RedirectToAction(nameof(Index));
                else
                    throw new Exception("Sucedio un error al intentar guardar el nuevo Estado");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(createStatusRequest);
            }
        }

        //GET: StatusController/Edit
        public async Task<IActionResult> Edit(int Id)
        {
            var status = await _mediator.Send(new GetStatusQuery(Id));
            return View(status.Adapt(new UpdateStatusRequest()));
        }

        //POST: StatustController/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(UpdateStatusRequest updateStatusRequest)
        {
            try
            {
                var result = await _mediator.Send(new UpdateStatusCommand(updateStatusRequest));
                if (result > 0)
                    return RedirectToAction(nameof(Index));
                else
                    throw new Exception("Sucedio un error al intentar editar estado");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(updateStatusRequest);
            }
        }


        //GET: StatusController/Delete
        public async Task<IActionResult> Delete(int Id)
        {
            var status = await _mediator.Send(new GetStatusQuery(Id));
            return View(status);
        }

        //POST: StatusController/Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, StatusResponse statusResponse)
        {
            try
            {
                var result = await _mediator.Send(new DeleteStatusCommand(id));
                if (result > 0)
                    return RedirectToAction(nameof(Index));
                else
                    throw new Exception("Sucedio un error al intentar eliminar el Estado");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(statusResponse);
            }
        }
    }
}

ExploreSV.WebApplication/Controllers/UserController.cs
using MediatR;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ExploreSV.BusinessLogic.DTOs;
using ExploreSV.BusinessLogic.UseCases.Users.Queries.GetUserAuthenticated;
using Microsoft.AspNetCore.Mvc.Rendering;
using Mapster;
using ExploreSV.BusinessLogic.UseCases.Users.Commads.CreateUser;
using ExploreSV.BusinessLogic.UseCases.Users.Commads.DeleteUser;
using ExploreSV.BusinessLogic.UseCases.Users.Queries.GetUser;
using ExploreSV.BusinessLogic.UseCases.Users.Queries.GetUsers;
using ExploreSV.BusinessLogic.UseCases.Roles.Queries.GetRoles;
using System.Security.Claims;

namespace ExploreSV.WebApplication.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IMediator _mediator;

        public UserController(IMediator mediator)
        {
            _mediator = mediator;
        }
        [AllowAnonymous]
        public async Task<IActionResult> CerrarSesion(string pReturnUrl = null)
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }
        [AllowAnonymous]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> Login(GetUserAuthenticatedQuery getUserAuthenticatedQuery)
        {
            try
            {
                var userResponse = await _mediator.Send(getUserAuthenticatedQuery);
                if (userResponse != null && userResponse.UserName == getUserAuthenticatedQuery.userName)
                {
                    var claims = new[]
                    {
                        new Claim(ClaimTypes.Name, userResponse.UserName),
                        new Claim("Id", userResponse.UserId.ToString())
                    };
                    var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(identity), new AuthenticationProperties { IsPersistent = true });
                    return RedirectToAction("Index", "Home");
                }
                else
                    throw new Exception("Credenciales incorrectas");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(getUserAuthenticatedQuery);
            }
        }

        public async Task<IActionResult> Index(int pageNumber = 1, int pageSize = 6)
        {
            var query = new GetUsersQuery
            {
                PageNumber = pageNumber,
                PageSize = pageSize
            };
            var users = await _mediator.Send(query);
            return View(users);
        }

        //GET: Create
        public async Task<IActionResult> Create()
        {
            var roles = await _mediator.Send(new GetRolesQuery());
            ViewData["RoleId"] = new SelectList(roles, "RoleId", "RoleName");
            return View();
        }

        //POST: Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateUserRequest createUserRequest)
        {
            try
            {
                var result = await _mediator.Send(new CreateUserCommand(createUserRequest));
                if (result > 0)
                    return RedirectToAction(nameof(Index));
                else
                    throw new Exception("Sucedio un error al intentar guardar el nuevo usuario");
            }
            catch (Exception ex)
            {
                var roles = await _mediator.Send(new GetRolesQuery());
                ViewData["RoleId"] = new SelectList(roles, "RoleId", "RoleName");
                ModelState.AddModelError("", ex.Message);
                return View(createUserRequest);
            }
        }

        //GET: Delete
        public async Task<IActionResult> Delete(int id)
        {
            var user = await _mediator.Send(new GetUserQuery(id));
            if (user == null)
                return NotFound(); // Manejar caso donde el usuario no existe
            return View(user);
        }

        //POST: Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int UserId)
        {
            try
            {
                var result = await _mediator.Send(new DeleteUserCommand(UserId));
                if (result > 0)
                    return RedirectToAction(nameof(Index));
                else
                    throw new Exception("Sucedio un error al intentar eliminar el Usuario");
                return RedirectToAction(nameof(Index)); // Redirige al index
                    
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                var user = await _mediator.Send(new GetUserQuery(UserId));
                return View("Delete", user);
            }
        }
    }
}

ExploreSV.WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExploreSV</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExploreSV.WebApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExploreSV</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="User" asp-action="Index">Usuarios</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Department" asp-action="Index">Departamentos</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Category" asp-action="Index">Categorias</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Status" asp-action="Index">Estados</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="TouristDestination" asp-action="Index">Destinos Turísticos</a>
                            </li>
                        </ul>
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <span class="nav-link user-name">@User.Identity.Name</span>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link logout-link" asp-area="" asp-controller="User" asp-action="CerrarSesion">Cerrar sesión</a>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @{
        var controller = ViewContext.RouteData.Values["Controller"]?.ToString();
        var action = ViewContext.RouteData.Values["Action"]?.ToString();
    }

    @* @if (controller == "Home" && action == "Index")
    {
        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <h5>ExploreSV</h5>
                        <p id="txtExplore">Tu mejor opción para conocer El Salvador</p>
                    </div>
                    <div class="col-md-4">
                        <h5>Conocenos</h5>
                        <ul class="list-unstyled">
                            <li><a asp-controller="Home" asp-action="MisionVision" class="footer-link">Misión y Visión</a></li>
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <h5>Contáctanos</h5>
                        <div class="contact-info">
                            <img src="~/images/arroba.png" alt="Email" class="contact-icon" />
                            <span>explore01SV@gmail.com</span>
                        </div>
                        <div class="contact-info">
                            <img src="~/images/llamar.png" alt="Teléfono" class="contact-icon" />
                            <span>+503 7624-6958</span>
                        </div>
                    </div>
                </div>

                <hr />
                <div class="text-center footer-content">
                    <span class="copyright">&copy; @DateTime.Now.Year</span> -
                    <span class="exploresv-white">ExploreSV</span>
                </div>
            </div>
        </footer>
    } *@

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>